### ISSUE TITLE
Implementation of statistical hypothesis tests.

### ISSUE THREAD

**Issue by marinang** [scikit-hep/scikit-stats#1]
I have developed in `lauztat` (https://github.com/marinang/lauztat) hypothesis tests like in `RooStats`, so the idea would be to take it here. However it depends on `zfit` is that ok?

The structure is like this:

* tests: discovery, upper limit, confidence interval
* calculators: asymptotic, frequentist
* configs: takes model/pdfs, data, loss builder, a minimiser ( and optionally sampling methods )

The calculator is fed by the config, and the test is fed by the calculator very similar to `RooStats`,  see an example here https://nbviewer.jupyter.org/github/marinang/lauztat/blob/master/examples/notebooks/discovery_zfit_freq.ipynb. Maybe it's not ideal and it's the right time to change it.

Finally where should we put it ? Under a `test`/`hypotest` submodule ?

**Comment by marinang** [comment]
@eduardo-rodrigues @HDembinski fell free to interact (and add anyone)

**Comment by marinang** [comment]
With the changes I propose in https://github.com/zfit/zfit/pull/156, this should make things easier/lighter since all the informations needed from the user will be accessible from a `likelihood`/`loss` or even a `FitResult` object .

- model
- data
- loss builder (for toys or asymov dataset)
- constraints

So this would reduce basically to two object `calculator` (or even `test_statistics`)  and `test` object.

**Comment by marinang** [comment]
After discussion with @eduardo-rodrigues we agreed that the `zfit` as fitting background is specific I would do like it is done in `awkward-array` with `awkward`/`awkward-numba`/`awkward-cpp` we could have a `hypotests`, that works with pure python and `hypotests-zfit` that works with `zfit`.

So in parallel to PR #2, I will write the basic classes for `hypotests`. This is a bit more complicated than the `hypotests-zfit` as the user will have to provide many informations such as 

- model / pdf (need to be able to sample for toys)
- data 
- loss functions / loss builder (for toys (frequentist test) or asymov dataset (test with asymptotic formulae))
- constraints
- informations on the free parameters in the models (limits, stepsize, initial value ...)
- best fit values (optional).

The pure python version might be easier to test and might serve as a cross-check to `hypotests-zfit`.

**Comment by marinang** [comment]
After further discussions with @mayou36, instead making submodules likes `hypotests` or `hypotests-zfit` we could require a standard fit API, as we discussed almost 1 year ago.
So from the `scikit-stats` side all the objects listed in previous comment should obey a standard API, i.e have some methods.
If another fitting library is used with `scikit-stats` but don't follow the standard API, it could be wrapped.
About standard API, I have used and tested `zfit` and it has a nice API, so for now I consider this is the standard API but of course we need to discuss about that.

What do you think? @eduardo-rodrigues @HDembinski

**Comment by HDembinski** [comment]
I haven't looked into zfit, but I don't have time to do this, so no objections from my side.
