### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/scikit-stats#8]
@marinang, is it possible to have Python 3.5 support for now at least? I'm asking having in mind the preparation of the `scikit-hep` metapackage and the fact that all packages it depends on do support 3.5. It would be nice to add `scikit-stats` to the gang … Thanks.

**Comment by marinang** [comment]
The thing is `zfit` needs python >= 3.6 (@mayou36  right?). So I can add it but I cannot test the `hypotests` submodule with python 3.5.

**Comment by eduardo-rodrigues** [comment]
Let's see what @mayou36 says …

But the code in this package should itself be OK with 3.5, right?

In any case one can decorate the tests to request Py3.6+. That's the easy part.

**Comment by marinang** [comment]
I have to check If I haven't put f-strings anywhere but otherwise the code is OK with python 3.5 .

**Comment by eduardo-rodrigues** [comment]
To be fair, I don't think we will need to support 3.5 for very long as I don't expect any sensible HEP experiment moving to Python 3 to start with 3.5 but rather with 3.6 or even 3.7 ;-). I know what I would do … LOL

**Comment by marinang** [comment]
If I quote [NPE 29](https://numpy.org/neps/nep-0029-deprecation_policy.html#nep-29-recommend-python-and-numpy-version-support-as-a-community-policy-standard)

> It shows the 42 month support windows for Python. A project with a major or minor version release in February 2019 should support Python 3.5 and newer, a project with a major or minor version released in December 2019 should support Python 3.6 and newer, and a project with a major or minor version release in November 2020 should support Python 3.7 and newer.

December is close enough to support 3.5 XD.

**Comment by mayou36** [comment]
Yes, zfit does not support 3.5. I would suggest to not support it until needed. And then the change can be made if necessary. But rather starting out with 3.6 seems for me the way to go.

**Comment by eduardo-rodrigues** [comment]
Folks, so you are suggesting that we only support 3.6 for the "metapackage release" of `scikit-hep`? I guess we can, and then we see if anyone complains ...
